### ISSUE TITLE
Can't run locally beause of `TypeError`

### ISSUE THREAD

**Issue by helfer** [apollostack/docs#141]
I ran into [this issue](https://github.com/hexojs/hexo/issues/1627) and had to disable highlighting to be able to run `hexo serve` locally. Not sure how to debug otherwise. @stubailo @tmeasday

**Comment by helfer** [comment]
Turned highlighting on again, not getting the error, but highlighting seems broken (no line numbers, only single lines highlighted, etc.). This is weird...

**Comment by tmeasday** [comment]
Hrmmm, I do see occasional flakiness with hexo that's typically fixed by removing the `db.json`

**Comment by helfer** [comment]
seems to be working for me now.
