### ISSUE TITLE
Custom scalar type, why prefixed with __

### ISSUE THREAD

**Issue by smeijer** [apollostack/docs#159]
Let me quote the docs first, so we know what I'm talking about:

> For this purpose, each scalar needs to define three methods: serialize, parseValue and parseLiteral. In Apollo, these functions are defined with the __ prefix: __serialize, __parseValue and __parseLiteral. Let's look at couple examples to demonstrate the potential of custom scalars.

So the question; is there a special reason to prefix this methods? I mean; let's compare with the example from the docs:

```js
export default {
  Date: {
    __name: 'Date',
    __serialize: (value) => value.getTime(),
    __parseValue: (value) => new Date(value),
    __parseLiteral: (ast) => parseInt(ast.value, 10),
  },
};
```

or without prefix:

```js
export default {
  Date: {
    name: 'Date',
    serialize: (value) => value.getTime(),
    parseValue: (value) => new Date(value),
    parseLiteral: (ast) => parseInt(ast.value, 10),
  },
};
```

In my opinion the latest looks a bit cleaner. But besides that: I also learned that it's a widely used convention to prefix private variables with `_`, so this makes our custom scalars look like we're doing something hacky, while it is just a documented feature.

**Comment by helfer** [comment]
The prefix is necessary to be able to tell them apart from a resolver for a field with the same name.

**Comment by stubailo** [comment]
Wait, but scalars can't have resolvers, right? So why do we need to differentiate?

**Comment by helfer** [comment]
Yeah, that's true, but I didn't feel like making a special case in the code, since we needed the __ for descripions anyway. Now that we don't need that any more, maybe it would be worth changing that. I can't do it at the moment, but if someone has time, I think it would make a great PR.

**Comment by stubailo** [comment]
Worth reopening this issue?

**Comment by stubailo** [comment]
Oh, I guess it would be a _new_ issue on graphql-tools. @smeijer if you're interested in working on this, please open an issue there to remove the need for the "dunderscore" (double underscore)
