### ISSUE TITLE
Suggestion: add example for  addSchemaLevelResolver

### ISSUE THREAD

**Issue by sebastienbarre** [apollostack/docs#163]
Would be great to see a small example (or Medium post) about [addSchemaLevelResolver](http://docs.apollostack.com/apollo-server/resolvers.html#addSchemaLevelResolver), if it's still there. Especially since it seems to pertain to authentication.
Thank you

**Comment by helfer** [comment]
@sebastienbarre I was actually thinking about removing the function altogether, because the use-case isn't quite clear. I would recommend doing authentication outside of GraphQL and then passing in the authorized user as part of the context.

**Comment by sebastienbarre** [comment]
@helfer makes sense, I assume you mean the `context` key in [the options passed to the server](http://docs.apollostack.com/apollo-server/setup.html)?
```
const ApolloOptions = {
  schema: GraphQLSchema,
  context?: any, // value to be used as context in resolvers
...
})
```

**Comment by helfer** [comment]
Yes, that's the one. It gets passed into every resolve function as the third argument.
