### ISSUE TITLE
Update Example apps with 0.3.0 gql breaking changes

### ISSUE THREAD

**Issue by abhiaiyer91** [apollostack/docs#64]

**Comment by stubailo** [comment]
It was pretty simple for meteor-starter-kit: https://github.com/apollostack/meteor-starter-kit/pull/8

**Comment by abhiaiyer91** [comment]
- [ ] Instagram
- [ ] Counter
- [ ] Shopping Cart
- [ ] sample server

**Comment by stubailo** [comment]
Wow, awesome work man

**Comment by abhiaiyer91** [comment]
all done

**Comment by stubailo** [comment]
You da best
