### ISSUE TITLE
could you provide some example about how to use watchQuery with react?

### ISSUE THREAD

**Issue by kadinwu** [apollostack/docs#66]
Per title.
Actually, i wanna to query some data by react-apollo query and also will get updated data if any data changes. 
Below is my code, but it only query data once, won't get any updated categories data. Anything wrong? Could u please provide some example for it in document? Thanks a lot.

import { connect } from 'react-apollo';
.......
function mapQueriesToProps() {
    return {
        categories: {
            query: gql`
          {
            categories{
              id
              title
              description
            }
          }
        `,
            forceFetch: false,
            returnPartialData: true,
            pollInterval: 250
        }
    };
}

export default connect({mapQueriesToProps})(Categories);

**Comment by stubailo** [comment]
@kadinwu I think we had a bug in `pollInterval` when used with `react-apollo` - can you try with the new versions of everything and see if it works?

Your code should definitely work, because `mapQueriesToProps` is supposed to be the same as `watchQuery`.

**Comment by stubailo** [comment]
Any updates?

**Comment by kadinwu** [comment]
Hi stubailo,

sorry for the late response.
with latest react-apollo version 0.3.4, the situation even worse, will see below error and cannot get result, previously, i am using version 0.3.1, please take a look.
store.js:11 Caught an exception! Error: Can't find field categories on object [object Object].(…)(anonymous function) @ store.js:11
store.js:12 Error: Can't find field categories on object [object Object].
    at diffFieldAgainstStore (webpack:///../~/apollo-client/data/diffAgainstStore.js?:120:19)
    at eval (webpack:///../~/apollo-client/data/diffAgainstStore.js?:51:22)
    at Array.forEach (native)
    at Object.diffSelectionSetAgainstStore (webpack:///../~/apollo-client/data/diffAgainstStore.js?:49:29)
    at Object.readSelectionSetFromStore (webpack:///../~/apollo-client/data/readFromStore.js?:28:37)
    at eval (webpack:///../~/apollo-client/QueryManager.js?:109:63)
    at eval (webpack:///../~/apollo-client/QueryManager.js?:276:13)
    at eval (webpack:///../~/lodash._basefor/index.js?:40:11)
    at baseForOwn (webpack:///../~/apollo-client/~/lodash.forown/index.js?:22:20)
    at forOwn (webpack:///../~/apollo-client/~/lodash.forown/index.js?:53:20)(anonymous function) @ store.js:12
es6.promise.js:119 Unhandled promise rejection Error: Can't find field categories on object [object Object].(…)

**Comment by jbaxleyiii** [comment]
@kadinwu what version of apollo-client are you using?

**Comment by stubailo** [comment]
Yeah this looks like a bug recently fixed in Apollo client

**Comment by kadinwu** [comment]
@johnthepink i am using 0.3.2. which version i can try? latest version 0.3.7?

**Comment by stubailo** [comment]
Yeah, update to the latest one.

**Comment by kadinwu** [comment]
ok, i will try later
thanks

**Comment by kadinwu** [comment]
@stubailo sorry for the late response, a little busy on other project. 
i just tried latest version 0.3.8, yes. it is working fine. Thank you very much.

**Comment by stubailo** [comment]
Great, glad it worked out!
