### ISSUE TITLE
Update docs to reflect new event names

### ISSUE THREAD

**Issue by stubailo** [apollostack/docs#80]
Also, this is a good opportunity to convert some of them to code snippets, rather than images, so that they are easier to update.

@abhiaiyer91 you interested?

**Comment by abhiaiyer91** [comment]
Yes. Assign to me

**Comment by helfer** [comment]
@abhiaiyer91 Is this done, or still in progress?

**Comment by abhiaiyer91** [comment]
Oh snap, I didnt even pay attention. Ill do it tonight

**Comment by abhiaiyer91** [comment]
Was on vacay will resume my activities now

**Comment by brunolemos** [comment]
@abhiaiyer91

**Comment by abhiaiyer91** [comment]
I still need to do this, unless
Someone else did!
