### ISSUE TITLE
Document how to use Redux devtools

### ISSUE THREAD

**Issue by stubailo** [apollostack/docs#9]

**Comment by stubailo** [comment]
Blocking on example apps, #8

**Comment by stubailo** [comment]
Just need to take some screenshots and put them in the docs!

**Comment by abhiaiyer91** [comment]
What exactly needs to be done here? Assign to me.

**Comment by stubailo** [comment]
@abhiaiyer91 I think this can be pretty simple, it's basically just expanding this section: http://docs.apollostack.com/apollo-client/devtools.html

I'd suggest a few screenshots of the dev tools chrome extension, demonstrating how different actions are fired when a query is initialized and the result comes back.

Bonus if you have any ideas about how to leverage time travel, etc.

**Comment by abhiaiyer91** [comment]
@stubailo time travel is going to be interesting. Will write up a spec and share

**Comment by stubailo** [comment]
Let's open that as a separate issue! I suspect that might require changes to apollo-client to be a lot more stateless.
