### ISSUE TITLE
Edit this page on GitHub links to wrong location

### ISSUE THREAD

**Issue by dburles** [apollostack/docs#97]

**Comment by helfer** [comment]
Could you fix this with a PR?

**Comment by tgdn** [comment]
On the theme, the line we are looking at is [this one](https://github.com/meteor/hexo-theme-meteor/blob/94485262479eabc1d9e9c8917570a5bb11530bf7/layout/page.ejs#L11), but on the [apollo config](https://github.com/apollostack/docs/blob/master/_config.yml#L36), it is the correct config. Other than that I don't quite get why it doesn't link to the correct github repo

**Comment by abhiaiyer91** [comment]
Which link is borked?

**Comment by stubailo** [comment]
Fixed, turns out there were two github links, and only one was broken
